language: node_js

node_js:
  - lts/*

cache:
  yarn: false
  npm: false

branches:
  only:
    - master
    - develop

jobs:
  include:
    - stage: build
      install: yarn --frozen-lockfile
      script: npm run build
    # Define the release stage that runs semantic-release
    - stage: release
      # Advanced: optionally overwrite your default `script` step to skip the tests
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
